<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="YP1009097DT" ignored="0" name="EmpManagementAPITestingUsingRestAssured" tests="8" failures="3" timestamp="27 May 2019 09:38:48 GMT" time="4.95" errors="0">
  <testcase name="deleteEmployeeWithJSONStringTest" time="3.04" classname="com.EmployeManagement.tests.EmployeeManagementTest"/>
  <testcase name="deleteEmployeeWithPayloadTest" time="1.447" classname="com.EmployeManagement.tests.EmployeeManagementTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [204]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [204]
at com.EmployeManagement.tests.EmployeeManagementTest.deleteEmployeeWithPayloadTest(EmployeeManagementTest.java:48)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- deleteEmployeeWithPayloadTest -->
  <testcase name="getAllEmployeesTest" time="0.057" classname="com.EmployeManagement.tests.EmployeeManagementTest"/>
  <testcase name="getEmployeeTest" time="0.131" classname="com.EmployeManagement.tests.EmployeeManagementTest"/>
  <testcase name="postEmployeeWithJSONStringTest" time="0.061" classname="com.EmployeManagement.tests.EmployeeManagementTest"/>
  <testcase name="postEmployeeWithPayloadTest" time="0.038" classname="com.EmployeManagement.tests.EmployeeManagementTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [204]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [204]
at com.EmployeManagement.tests.EmployeeManagementTest.postEmployeeWithPayloadTest(EmployeeManagementTest.java:28)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- postEmployeeWithPayloadTest -->
  <testcase name="putEmployeeWithJSONStringTest" time="0.03" classname="com.EmployeManagement.tests.EmployeeManagementTest"/>
  <testcase name="putEmployeeWithPayloadTest" time="0.021" classname="com.EmployeManagement.tests.EmployeeManagementTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [204]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [204]
at com.EmployeManagement.tests.EmployeeManagementTest.putEmployeeWithPayloadTest(EmployeeManagementTest.java:38)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- putEmployeeWithPayloadTest -->
</testsuite> <!-- EmpManagementAPITestingUsingRestAssured -->
